### ISSUE TITLE
Main thread lost connection to MySQL after generating 48k warehouses

### ISSUE THREAD

**Issue by vbienf** [TPC-Council/HammerDB#734] opened 2024-08-18 09:12 UTC
**Guidance**
Bug reports are for when HammerDB is not behaving as expected.
Bug reports should not be submitted for help in understanding database performance related questions.
General questions on database performance or HammerDB usability should be submitted under Discussions.

**Describe the bug**
Generating 48K warehouses using 100 virtual users for a MySQL database took more than 24 hours. After the generation, the main virtual user encountered an error: "Error in virtual user 1: Error: mysqlexec/db server: Lost connection to MySQL server during query" while trying to create stored procedures.

**To Reproduce**
1. Using the GUI, start generating 48K warehouses on your MySQL database.
2. After the generation is complete, observe the error.

**Expected behavior**
If data generation takes more than 24 hours, it’s likely that all your connections will be lost. I expect that there should be a check before creating stored procedures and after data generation. In the case where the main virtual user loses connection, it should try to reconnect and perform a sanity check to ensure that the number of rows in the warehouse table matches the expected number from the parameter "$mysql_count_ware." Or simply check if the connection is lost and reconnect once to continue.

**Screenshots**
![image](https://github.com/user-attachments/assets/2719bdfc-214c-4e31-8166-9cece11adca0)

**HammerDB Version (please complete the following information):**
 - Version: 4.7
 - Build: Release download

**HammerDB Interface (please complete the following information):**
 - UI: GUI

**Operating System (please complete the following information):**
 - Server OS: CentOS 7.4
 - Client OS: RHEL 9.3

**Database Server (please complete the following information):**
 - Database name: MySQL
 - Database Release Version: 5.7.20

**Database Client (please complete the following information):**
 - Database client name: mysql

**Additional context**
I understand that using the script editor, I can run only the last two functions, "CreateStoredProcs" and "GatherStatistics," or execute these SQLs myself, so it’s not a critical bug. But I still think it’s a bug because this error can be easily reproduced when generating a large dataset.

**Comment by sm-shaw** [comment] 2024-08-19 09:32
I would not describe this as a bug as HammerDB is working as expected. Also in MySQL you can set the wait_timeout parameter that by default is 28800 seconds (8 hours) - so if the build is taking longer than this then you can set database parameters to ensure that the connection is not closed on the database side after remaining idle waiting for the build. 

However, when creating a large dataset to use the default build to take more than 24 hours is almost certainly the wrong way to do it. 

The default build using inserts offers the most convenience, however you are logging all the transactions and maintaining consistency and recoverability as you do, so it is not going to be the quickest way by any means. Instead, you can use the datagen https://www.hammerdb.com/docs/ch13.html feature to generate the dataset as flat files, use SQL to create the schema and then bulk load them using an external tool bypassing the normal database logging. You then use SQL to create the stored procedures copied from a smaller template build. 

As a test we created 10000 warehouses in flat files in 24 minutes, example below. So although it takes a bit more work and requires additional storage for staging, overall it is a lot quicker to use a datagen based build than an insert based build. 
```
hammerdb>dbset db maria
Database set to MariaDB

hammerdb>dbset bm TPROC-C
Benchmark set to TPROC-C for MariaDB

hammerdb>dgset warehouse 10000

hammerdb>dgset vu 112
Set virtual users to 112 for data generation

hammerdb>dgset directory "/data/TPCCDATA"

hammerdb>print datagen
Data Generation set to build a TPC-C schema for MariaDB with 10000 warehouses with 112 virtual users in /data/TPCCDATA

hammerdb>datagenrun
....
Vuser 113:End:Mon Aug 19 01:55:42 PDT 2024
Vuser 113:FINISHED SUCCESS
Vuser 1:Workers: 0 Active 112 Done        
Vuser 1:10000 WAREHOUSE SCHEMA GENERATED in 24 MINUTES         
Vuser 1:FINISHED SUCCESS
ALL VIRTUAL USERS COMPLETE
```
It is worth noting that a potential enhancement has been raised before to break the schema build down into steps, that can be isolated, e.g. separate steps of  create database, create tables, load data, create stored procedures, create indexes, gather statistics. Then if doing the external build you can choose to just create tables, create stored procedures etc without having to do it manually. Some environments have scripts to do this that can easily be re-run for schema builds.  However, this enhancement has not reached the top of the run queue as in the vast majority of cases the default build is sufficient. (Also for some databases such as SQL Server HammerDB uses a bulk insert by default).  it would be welcome if anyone who desires this feature to break the build into steps to submit a pull request to do it. 

There is already a separate schema check that will check the table counts, stored procedures as well as data consistency according to the TPC-C specification rules.

**Comment by sm-shaw** [comment] 2024-08-23 07:14
No further so closing as not a bug as other more efficient options available to create large schemas.

**Closed by sm-shaw** 2024-08-23 07:14 UTC
