### ISSUE TITLE
hammerdbcli: can't find package ticklecharts

### ISSUE THREAD

**Issue by josephcolton** [TPC-Council/HammerDB#624] opened 2023-10-18 20:19 UTC
**Describe the bug**
When starting hammerdbcli, I am presented with the following error message:

HammerDB CLI v4.9
Copyright (C) 2003-2023 Steve Shaw
Type "help" for a list of commands
While loading module "ticklecharts"...
can't find package ticklecharts
    while executing
"package require $m "

I was able to edit the hammerdbcli file and remove the ticklecharts from the module list on line 82 to make it work.

**To Reproduce**
On a Ubuntu 22.04 system:

git clone https://github.com/TPC-Council/HammerDB.git
sudo apt -y install wish tclsh
sudo apt-get install -y tcl-thread libsqlite3-tcl tcl-expect mysqltcl
cd HammerDB
mkdir bin; cd bin; ln -s /usr/bin/tclsh8.6; cd ..
./hammerdbcli

**Expected behavior**
I expected to run.

**HammerDB Version (please complete the following information):**
 - Version: 4.9
 - Build: git source

**HammerDB Interface (please complete the following information):**
 - UI: CLI

**Operating System (please complete the following information):**
 - Server OS: Ubuntu

**Database Server (please complete the following information):**
 - Database name: MySQL

**Comment by sm-shaw** [comment] 2023-10-21 14:46
Closed as not a bug.
 [v4.9](https://github.com/TPC-Council/HammerDB/releases/tag/v4.9) is now available as a pre-built binary.

**Closed by sm-shaw** 2023-10-21 14:46 UTC
