### ISSUE TITLE
 Postgres datatype change from number to integer performance degragation 

### ISSUE THREAD

**Issue by greenhal** [TPC-Council/HammerDB#194] opened 2021-02-15 17:51 UTC
I noticed a drop in performance with the table column datatype change from number to integer, introduced in commit 9b0305e3eab18af589aad6c5bf219bd7d011318f (1/26/2021).

Performance dropped about 30%.    I was able to trace to the payment procedure, 
Specifically the INOUT parameter p_c_id.

When defined as a NUMERIC(5,0),  the query plan does does not use the full index (c_w_id, c_d_id , c_id), it does scan on c_w_id, c_d_id and filter on c_id,

When defined as a INTEGER, the query plan does use the full index,

_**NUMERIC query plan:**_

2021-02-12 18:27:27.993 UTC [16541] LOG: duration: 2.390 ms plan:
Query Text: SELECT c_first, c_middle, c_last, ,,,
FROM customer
WHERE c_w_id = p_c_w_id AND c_d_id = p_c_d_id AND c_id = p_c_id
**Index Scan using customer_i1 on customer (cost=0.43..5738.56 rows=15 width=130) (actual time=2.388..2.388 rows=1 loops=1)
*Index Cond: ((c_w_id = 28) AND (c_d_id = 3))*
*Filter: ((c_id)::numeric = '2998'::numeric)*
Rows Removed by Filter: 2997**
2021-02-12 18:27:27.993 UTC [16541] CONTEXT: SQL statement "SELECT c_first, c_middle, c_last ,,,
FROM customer
WHERE c_w_id = p_c_w_id AND c_d_id = p_c_d_id AND c_id = p_c_id“
PL/pgSQL function payment(integer,integer,integer,integer,integer,numeric,character,.. ) line 41 at SQL statement

_**INTEGER query plan:**_

2021-02-12 19:05:16.670 UTC [19065] LOG: duration: 0.009 ms plan:
Query Text: SELECT c_first, c_middle, c_last, ...
FROM customer
WHERE c_w_id = p_c_w_id AND c_d_id = p_c_d_id AND c_id = p_c_id
**Index Scan using customer_i1 on customer (cost=0.43..8.45 rows=1 width=130) (actual time=0.008..0.008 rows=1 loops=1)
*Index Cond: ((c_w_id = 47) AND (c_d_id = 1) AND (c_id = 746))***
2021-02-12 19:05:16.670 UTC [19065] CONTEXT: SQL statement "SELECT c_first, c_middle, c_last, ...
FROM customer
FROM customer
WHERE c_w_id = p_c_w_id AND c_d_id = p_c_d_id AND c_id = p_c_id“
PL/pgSQL function payment(integer,integer,integer,integer,integer,numeric,character,...) line 41 at SQL statement

Regards

**Comment by sm-shaw** [comment] 2021-02-16 18:32
Many thanks for raising. In testing this gave appx 3% which was considered worth adding as the guidance came from the PostgreSQL community. However clearly from the trace this does cause an issue. I will investigate to reproduce and suspect a mismatch between the function/stored procedure definition and what the tables have been changed to.  
So initially is the issue with the functions/stored procedures or both? 
As this change will go into v4.1 it does not impact a current release and there is the option of backing out if a satisfactory resolution cannot be found.  This issue will need to be resolved and any degradation fixed to go ahead with the changes.

**Comment by greenhal** [comment] 2021-02-16 18:49
It looks like it was changed for function already…

https://github.com/TPC-Council/HammerDB/blob/master/src/postgresql/pgoltp.tcl#L1351



Regards,
Mark Greenhalgh
DBE RDS Benchmarking
greenhal<https://phonetool.amazon.com/users/greenhal>
greenhal@amazon.com<mailto:greenhal@amazon.com>

**Comment by vik-fearing-edb** [comment] 2021-02-17 13:05
Hi.  I'm not seeing the same plan here (I'm the one who originally changed the column types).  As per @greenhal's comment above, the `c_id` variable appears to be integer already so the query should use the index fully and not use any filters.  That's what the report appears to be saying anyway so I admit I'm a bit confused. 😃 

Regardless of any of that, the parameter `p_c_id_in` should be of type integer as well.

**Comment by sm-shaw** [comment] 2021-02-17 14:13
Also worth noting that I tested on PostgreSQL 13.1 although I would not think that the PostgreSQL version should make too much difference. 

For additional clarity in the build and driver script https://github.com/TPC-Council/HammerDB/blob/master/src/postgresql/pgoltp.tcl the build is defined in proc build_pgtpcc, this contains the table and index definitions and there are 3 places where the functions/stored procedures are defined in the build script depending on the chosen options, so there is:

1. EDB Oracle compatible (these have not been updated for a while) 
2. PostgreSQL Functions 
3. PostgreSQL Stored Procedures

It is the functions above that give the reported problem although I don't know if the stored procedures have been tested.  In the driver scripts if functions are chosen HammerDB uses prepared statements but not for stored procedures as prepared statements are (or were?) not supported for stored procedures when they were written.  Conversely functions do not support INOUT parameters. 

Again depending on the options chosen the driver script may be built in different ways so in the source file 
`proc fn_prep_statement ...` can be found defined 4 times, once in insert_pgconnectpool_drivescript (for the connect pool version of the driver), once in loadpgtpcc for the test version of the driver script and twice in loadtimedpgtpcc (once for synchronous and once for asynchronous).  

So making a change in the source might not necessarily reach the loaded driver script depending on the options and any eventual changes will need to be made in all locations so that they are the same.

**Comment by sm-shaw** [comment] 2021-02-17 14:26
Having written that and apologies @greenhal as you cleary said specifically the INOUT parameter p_c_id, so this would indicate the stored procedures rather than the functions as desribed above, In the stored procedure p_c_id is defined as follows:
https://github.com/TPC-Council/HammerDB/blob/cceafe69b9aa88815bc4eba664e443a42e67be7e/src/postgresql/pgoltp.tcl#L806
whereas in the function it is an INT but p_c_id_in is NUMERIC https://github.com/TPC-Council/HammerDB/blob/cceafe69b9aa88815bc4eba664e443a42e67be7e/src/postgresql/pgoltp.tcl#L1351
and in fn_prep_statement (in all places) for the functions it is also NUMERIC `set prep_payment "prepare payment (INTEGER, INTEGER, INTEGER, INTEGER, NUMERIC, INTEGER, NUMERIC, VARCHAR)`
So it could be possible that the stored procedures see the issue rather than the functions.

**Comment by vik-fearing-edb** [comment] 2021-02-17 14:37
Ok, I can see (by looking, not testing) that the stored procedure would have the problem described.  My installation uses the functions.  My mistake, sorry.

Also, functions have supported INOUT parameters since 8.1, released in 2005...

**Comment by sm-shaw** [comment] 2021-02-17 14:54
Many thanks, I did not want to change the functions too much and instead added this to the stored procedures, however it was the prepared statements that I did not believe was supported with stored procedures or at least I could not find a way of getting them to work.  (The equivalent of prepared statements is used for the stored procedures for the other databases).

**Comment by vik-fearing-edb** [comment] 2021-02-17 17:19
What I would suggest is to use the syntax `customer.c_id%type` in the declarations, and not give the type list at all in the `prepare` statements.

**Comment by sm-shaw** [comment] 2021-02-18 11:09
Many thanks for the feedback, I will fix the datatypes and update the modified schema.

**Closed** 2021-03-05 17:43 UTC
Labels: bug
