### ISSUE TITLE
HammerDB fails after database failover scenario

### ISSUE THREAD

**Issue by marjus45** [TPC-Council/HammerDB#573] opened 2023-06-23 07:37 UTC
**Describe the bug**

I am trying to run the HammerDB with database failover against my PostgreSQL database, in an effort to stress test my database, and see how it recovers in various scenarios such as replication, etc.

I tried following this issue https://github.com/TPC-Council/HammerDB/issues/153, on which I set the appropriate parameters, according to that issue. When I kill the connection for a while, and then re-estate, I saw the Virtual Users re-connect, but that wasn't the case for the Transaction Counter thread.

After the connection is established again, the Virtual Users state:
```
Vuser 10:RUNNING
Vuser 10:VU 10 : Assigning WID=9 based on VU count 16, Warehouses = 80 (1 out of 5)
Vuser 10:VU 10 : Assigning WID=25 based on VU count 16, Warehouses = 80 (2 out of 5)
Vuser 10:VU 10 : Assigning WID=41 based on VU count 16, Warehouses = 80 (3 out of 5)
Vuser 10:VU 10 : Assigning WID=57 based on VU count 16, Warehouses = 80 (4 out of 5)
Vuser 10:VU 10 : Assigning WID=73 based on VU count 16, Warehouses = 80 (5 out of 5)
Vuser 10:Processing 10000000 transactions with output suppressed...
```

but the Virtual User 1 logs:
```
Vuser 1:Rampup 2 minutes complete ...
Vuser 1:Rampup complete, Taking start Transaction Count.
Error in Virtual User 1: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

Vuser 1:FINISHED FAILED
Vuser 1:RUNNING
Vuser 1:Beginning rampup time of 2 minutes
Vuser 1:Rampup 1 minutes complete ...
Vuser 1:Rampup 2 minutes complete ...
Vuser 1:Rampup complete, Taking start Transaction Count.
Vuser 1:Timing test period of 5 in minutes
Vuser 1:1 ...,
Vuser 1:2 ...,
Vuser 1:3 ...,

...

Warning: a running Virtual User was terminated, any pending output has been discarded
Vuser 1:FINISHED FAILED
```

After some other logs, we see the following
```
Virtual Users remain running in background or shutting down, retry
Transaction Counter is not running
TEST COMPLETE
```

I understand that these logs came from `vudestroy()` and `tcstop()` from the **run script**.

Lastly I see from the results script the following:
```
root@hammerdb:/home/hammerdb/HammerDB-4.7# ./hammerdbcli py auto /bin/pg_tprocc_result.py
HammerDB CLI v4.7
Copyright (C) 2003-2023 Steve Shaw
Type "help()" for a list of commands
exec(open('/bin/pg_tprocc_result.py').read())
hammerdb>>>exec(open('/bin/pg_tprocc_result.py').read())
stdout off /home/hammerdb/HammerDB-4.7/TMP/pg_tprocc_6492AFEA5FE903E253834383.out

TRANSACTION RESPONSE TIMES
No Timing Data for JOB 6492AFEA5FE903E253834383: jobs jobid timing

TRANSACTION COUNT
{"PostgreSQL tpm PostgreSQL {sql failed server closed the connection unexpectedly This probably means the server terminated abnormally before or while processing the request.}": {
    "0": "2023-06-21 08:08:30",
    "23460": "2023-06-21 08:08:20"
  }}

HAMMERDB RESULT
[
  "6492AFEA5FE903E253834383",
  "Jobid has no test result"
]
```

See below for full logs.

**To Reproduce**

1. Create a PostgreSQL database
1. Configure the hammerdb to run against that database
1. Run HammerDB build schema with the default parameters
1. In the "run" script configure
    a. `diset('tpcc','pg_raiseerror','true')`
    b. `vuset('iterations',1000)`
    c. `vuset('repeat',3000)`
1. Start the script
1. Once the transaction counter has started to output "tpm" results, kill the
   PostgreSQL connection with SIGKILL in the process.
1. Re-estate the PostgreSQL connection (i.e. re-spawn the process), if not done automatically

**Expected behavior**

The expected behavior would be for the test to continue printing "tpm" results, when the connection of the Vusers is re-estated, as was before the connection is lost.

**HammerDB Version (please complete the following information):**
 - Version: 4.7
 - Build: Release download (digest:sha256:d0df547d32a028a884adc3d7eb39b28e8a074dd42811eea61b4404c186307c63)

**HammerDB Interface (please complete the following information):**
 - CLI

**Operating System (please complete the following information):**
 - Client OS: Container which uses Ubuntu 20.04

**Database Server (please complete the following information):**
 - Database name: PostgreSQL
 - Database Release Version: 15.3

**Additional context**

The log of my test run can be found here [killtheleader-SIGKILL-delay500.log](https://github.com/TPC-Council/HammerDB/files/11845890/killtheleader-SIGKILL-delay500.log)

**Comment by sm-shaw** [comment] 2023-06-23 15:15
OK, so this is not a bug, as it has never been intended behaviour that the user kills connections during the test and is then expected to receive meaningful benchmark results.

Also, if you failed over to a different system then the TPM on the replica would be out of synch with the primary and the monitor VU queries the TPM and NOPM at the start and end of the test, so it is not impacting the workload during the test. It is not querying the database during the test. 

The transaction counter thread makes an additional connection to report the TPM (or QPH) aside from the Virtual Users, however this also is not intended to reconnect if the database fails or the connection is killed. It is not entirely clear that we would want to try and reconnect, as in the vast majority of use cases it is not expected to kill connections or close the database. 

If you want to submit a PR to change the behaviour you can do and this would be reviewed by the TPC-OSS to determine if this is functionality that is desired so please advise if you are interested in doing this.

**Comment by marjus45** [comment] 2023-06-26 11:45
Hi @sm-shaw and thanks for the reply.

> as it has never been intended behaviour that the user kills connections during the test and is then expected to receive meaningful benchmark results.

I am a bit confused by the above since in this issue https://github.com/TPC-Council/HammerDB/issues/153 I understand that you intended for supporting failover scenarios, and I quote from the issue:

> Once reconnected the workload would continue. This will enable the measurement of how long a database outage took to return to full performance.

It is my understanding that the feature said supported on that issue, is not working correctly, since after the Virtual Users are re-connected we don't have any measurements, and the users actually report "FINISHED FAILED" after a while. Are you saying that the support for failover ends before the "result reporting"?

If that is the case, I think that we should add that support since otherwise the test seems failing, instead of re-connecting and continuing as before. I would like to help by making a PR for this, but I might need your help in understanding the existing codebase.

Considering a fix for the above, I understand that for the Virtual Users there is already a "Retry" procedure here https://github.com/TPC-Council/HammerDB/blob/master/src/generic/genvu.tcl#L248-L260. Is this correct?

Would it make sense to add a similar procedure for the Transaction Counter Thread, for example wrap with a similar for loop this function call here https://github.com/TPC-Council/HammerDB/blob/master/src/generic/gencli.tcl#L1607C18-L1607C18 ?

It would be helpful if you could give me an initial draft of a solution so that I can start working on this issue.

**Comment by sm-shaw** [comment] 2023-06-27 14:54
HammerDB has many test scenarios including the ability to write your own. This includes the ability to log off and on and run a script multiple times. That is the section you highlight. 
It has never been the intention for the monitor virtual user or transaction counter to reconnect after the connection is killed from the perspective that once the connection is killed performance numbers are no longer valid. 
The vast majority of users are not killing connections while the workload is running. 
So yes the ability to log on and off multiple times is a feature and yes this will allow the active virtual users to reconnect after a failure, however this was not the original intention of the feature, it is simply a scenario that can be tried whatever the user wishes. 
You are more than welcome to implement a reconnect feature, however this will need to be able to be turned off or limited to a number of tries and HammerDB supports multiple databases which all have different failover scenarios meaning a solution will need to work for all of them (on both Windows and Linux).

**Comment by sm-shaw** [comment] 2023-11-03 11:37
Closed as not planning on extending HammerDB fully for failover scenarios at the current time.

**Closed by sm-shaw** 2023-11-03 11:37 UTC
