### ISSUE TITLE
Benchmark Singlestore with hammerDB

### ISSUE THREAD

**Issue by dhgokul** [TPC-Council/HammerDB#657] opened 2024-01-15 19:26 UTC
Can you please provide details on whether load testing can be performed using HammerDB for singlestore?
https://www.singlestore.com/

I configured hammercli in Redhat OS. Installed the SQL client executed the 'librarycheck', and confirmed the ODBC connector loaded successfully for MySQL. However, when I created a tcl file with the engine set as SIngleStore, I encountered an issue. PFA
![Screenshot 2024-01-15 at 19 17 20](https://github.com/TPC-Council/HammerDB/assets/5689804/179d6a91-7293-4584-a279-5ca1cf123d47)
![Screenshot 2024-01-15 at 19 20 24](https://github.com/TPC-Council/HammerDB/assets/5689804/cd06fb05-a270-4534-889b-dcd26b640362)

**Comment by sm-shaw** [comment] 2024-01-16 12:36
Closed as duplicate of discussion question

**Closed** 2024-01-16 12:36 UTC
