### ISSUE TITLE
Linux 4.6 message error when using sqlitedb_dir != TMP

### ISSUE THREAD

**Issue by mdedlow** [TPC-Council/HammerDB#476] opened 2022-12-22 15:07 UTC
I set sqlitedb_dir to "/foo" and it works, but the feedback says it's using /tmp:

$ grep foo config/generic.xml
	   <sqlitedb_dir>/foo</sqlitedb_dir>

$ ls -l /foo/
total 0

$ ./hammerdbcli
HammerDB CLI v4.6
Copyright (C) 2003-2022 Steve Shaw
Type "help" for a list of commands
Initialized SQLite on-disk database **/tmp/hammer.DB** using existing tables (36,864 KB)

$ ls  /foo
database.db  db2.db  generic.db  mariadb.db  mssqlserver.db  mysql.db  oracle.db  postgresql.db

**Comment by sm-shaw** [comment] 2022-12-22 18:05
There are 2 SQLite storage locations. The one you have changed is for the XML config to be persistent over restarts. The one you are looking for is in the CLI section of the generic.xml file. By default they are both set to TMP (which means find a suitable temp directory).

**Comment by sm-shaw** [comment] 2022-12-24 11:02
Closed as not a bug. Persistent Configuration is set here:
```
<hammerdb>
   <theme>
        <scaling>auto</scaling>
        <scaletheme>auto</scaletheme>
        <pixelsperpoint>auto</pixelsperpoint>
   </theme>
   <sqlitedb>
        <sqlitedb_dir>TMP</sqlitedb_dir>
   </sqlitedb>
```

jobs output storage is set here:

```
    <commandline>
	<sqlite_db>TMP</sqlite_db> 
        <keepalive_margin>10</keepalive_margin>
        <jobsoutput>JSON</jobsoutput>
        <jobs_disable>0</jobs_disable>
    </commandline>
```

**Closed by sm-shaw** 2022-12-24 11:02 UTC
