### ISSUE TITLE
No Random warehouse selection in 4.0

### ISSUE THREAD

**Issue by ek1220** [TPC-Council/HammerDB#191] opened 2021-01-18 09:20 UTC
Hello,
It looks like the warehouse selection in 4.0 is not randomized. For example I have an Oracle database with 1600 warehouses and only warehouses >1000 are selected. With each run always the same. (see screenshot)

<img width="503" alt="user-AW" src="https://user-images.githubusercontent.com/75491045/104895848-aa1d6c00-5976-11eb-8420-3068cdfa435e.png">

I tested with all warehouses and it seems this does not work either. 

Thank you,
   erich

**Comment by sm-shaw** [comment] 2021-01-18 15:15
Many thanks for the Issue.  To clarfiy exactly where the problem is, by default the Warehouse ID chosen by each Virtual User is different compared to when running the use all warehouse option.  By default each Virtual User chooses one Warehouse ID at random at the start of the run and stays with it for the duration of the test for all transactions.  It does this by finding the maximum warehouse id configured and then choosing a number betweeen 1 and this figure at random, storing this in the variable $w_id.  it does not print this out however you can check it as follows.  I would recommend setting total_iterations to 1 and adding a "puts $w_id" statement as shown. Then you will see printed out the w_id chosen each time. In my tests this works as intended and is random. So we need to clarify if this is where the problem is and how to reproduce it.
```
set total_iterations 1 ;# Number of transactions before logging off
...
set sql1 "select max(w_id) from warehouse"
set w_id_input [ standsql $curn1 $sql1 ]
#2.4.1.1 set warehouse_id stays constant for a given terminal
set w_id  [ RandomNumber 1 $w_id_input ]  
...
puts "Warehouse ID chosen is $w_id"
```
On the other hand "use all warehouses" option is not initially randomized and instead divides out all of the available warehouses between the Virtual Users and then changes the w_id from its available pool for each transaction at random. 
 The screenshot shows the Use All warehouses output, however the text says all warehouses doesn't work either. The screenshot doesn't show the complete output as it starts from assigned warehouse 8 out of 11. eg for VUser 2 the eighth warehouse assigned was 1044, What warehouses were assigned from 1 to 7 before this point?  You would need to create a logfile and attach that with all of the output to show the output that in the screenshot has already scrolled past. 
I will test this on a schema with > 1000 warehouses but please provide clarity on the questions.
1) Is there a problem with the default random warehouse allocation, how can we reproduce this. 
2) What is the complete warehouse allocation for "use all warehouses" including allocated warehouse 1 to 7 for your example in addition to the output shown for allocated warehouses 8 to 11.

**Comment by sm-shaw** [comment] 2021-01-19 11:00
I have tested from a 1500 warehouse schema. (I am using SQL Server but the code for warehouse selection is the same). 
Firstly the default random allocation where 1 warehouse is chosen at random at the start and is then kept for the duration of the test. As shown for both the test and timed workload the warehouse selection is random and uses the full allocation of the warehouse count which is correctly selected from the schema. 

Here is the output from the test workload
```
Vuser 1:Chose Warehouse 890 from max of 1500
Vuser 1:Processing 1 transactions without output suppressed...
Vuser 1:new order
Vuser 2:Chose Warehouse 41 from max of 1500
Vuser 2:Processing 1 transactions without output suppressed...
Vuser 2:payment
Vuser 3:Chose Warehouse 118 from max of 1500
Vuser 3:Processing 1 transactions without output suppressed...
Vuser 3:new order
Vuser 4:Chose Warehouse 1186 from max of 1500
Vuser 4:Processing 1 transactions without output suppressed...
Vuser 4:payment
Vuser 5:Chose Warehouse 1021 from max of 1500
Vuser 5:Processing 1 transactions without output suppressed...
Vuser 5:payment
Vuser 6:Chose Warehouse 325 from max of 1500
Vuser 6:Processing 1 transactions without output suppressed...
Vuser 6:payment
Vuser 7:Chose Warehouse 217 from max of 1500
Vuser 7:Processing 1 transactions without output suppressed...
Vuser 7:new order
Vuser 8:Chose Warehouse 465 from max of 1500
Vuser 8:Processing 1 transactions without output suppressed...
Vuser 8:new order
Vuser 9:Chose Warehouse 883 from max of 1500
Vuser 9:Processing 1 transactions without output suppressed...
Vuser 9:payment
Vuser 10:Chose Warehouse 33 from max of 1500
Vuser 10:Processing 1 transactions without output suppressed...
Vuser 10:payment
```
Here is the output from the timed workload
```
Vuser 2:Chose Warehouse 1087 from max of 1500
Vuser 2:Processing 1 transactions with output suppressed...
Vuser 3:Chose Warehouse 579 from max of 1500
Vuser 3:Processing 1 transactions with output suppressed...
Vuser 4:Chose Warehouse 375 from max of 1500
Vuser 4:Processing 1 transactions with output suppressed...
Vuser 5:Chose Warehouse 1222 from max of 1500
Vuser 5:Processing 1 transactions with output suppressed...
Vuser 6:Chose Warehouse 935 from max of 1500
Vuser 6:Processing 1 transactions with output suppressed...
Vuser 7:Chose Warehouse 227 from max of 1500
Vuser 7:Processing 1 transactions with output suppressed...
Vuser 8:Chose Warehouse 157 from max of 1500
Vuser 8:Processing 1 transactions with output suppressed...
Vuser 9:Chose Warehouse 411 from max of 1500
Vuser 9:Processing 1 transactions with output suppressed...
Vuser 10:Chose Warehouse 939 from max of 1500
Vuser 10:Processing 1 transactions with output suppressed...
Vuser 11:Chose Warehouse 547 from max of 1500
Vuser 11:Processing 1 transactions with output suppressed...
```
Now 'for use all warehouses' the example shows 10 virtual users with 1500 warehouses so each virtual user is allocated 150 warehouses each. The output shows all of virtual user 2 and the end of virtual user 11. (remember VU1 is a monitor). 
```
Vuser 2:VU 2 : Assigning WID=1 based on VU count 10, Warehouses = 1500 (1 out of 150)
Vuser 2:VU 2 : Assigning WID=11 based on VU count 10, Warehouses = 1500 (2 out of 150)
Vuser 2:VU 2 : Assigning WID=21 based on VU count 10, Warehouses = 1500 (3 out of 150)
Vuser 2:VU 2 : Assigning WID=31 based on VU count 10, Warehouses = 1500 (4 out of 150)
Vuser 2:VU 2 : Assigning WID=41 based on VU count 10, Warehouses = 1500 (5 out of 150)
Vuser 2:VU 2 : Assigning WID=51 based on VU count 10, Warehouses = 1500 (6 out of 150)
Vuser 2:VU 2 : Assigning WID=61 based on VU count 10, Warehouses = 1500 (7 out of 150)
Vuser 2:VU 2 : Assigning WID=71 based on VU count 10, Warehouses = 1500 (8 out of 150)
Vuser 2:VU 2 : Assigning WID=81 based on VU count 10, Warehouses = 1500 (9 out of 150)
Vuser 2:VU 2 : Assigning WID=91 based on VU count 10, Warehouses = 1500 (10 out of 150)
Vuser 2:VU 2 : Assigning WID=101 based on VU count 10, Warehouses = 1500 (11 out of 150)
Vuser 2:VU 2 : Assigning WID=111 based on VU count 10, Warehouses = 1500 (12 out of 150)
Vuser 2:VU 2 : Assigning WID=121 based on VU count 10, Warehouses = 1500 (13 out of 150)
Vuser 2:VU 2 : Assigning WID=131 based on VU count 10, Warehouses = 1500 (14 out of 150)
Vuser 2:VU 2 : Assigning WID=141 based on VU count 10, Warehouses = 1500 (15 out of 150)
Vuser 2:VU 2 : Assigning WID=151 based on VU count 10, Warehouses = 1500 (16 out of 150)
Vuser 2:VU 2 : Assigning WID=161 based on VU count 10, Warehouses = 1500 (17 out of 150)
Vuser 2:VU 2 : Assigning WID=171 based on VU count 10, Warehouses = 1500 (18 out of 150)
Vuser 2:VU 2 : Assigning WID=181 based on VU count 10, Warehouses = 1500 (19 out of 150)
Vuser 2:VU 2 : Assigning WID=191 based on VU count 10, Warehouses = 1500 (20 out of 150)
Vuser 2:VU 2 : Assigning WID=201 based on VU count 10, Warehouses = 1500 (21 out of 150)
Vuser 2:VU 2 : Assigning WID=211 based on VU count 10, Warehouses = 1500 (22 out of 150)
Vuser 2:VU 2 : Assigning WID=221 based on VU count 10, Warehouses = 1500 (23 out of 150)
Vuser 2:VU 2 : Assigning WID=231 based on VU count 10, Warehouses = 1500 (24 out of 150)
Vuser 2:VU 2 : Assigning WID=241 based on VU count 10, Warehouses = 1500 (25 out of 150)
Vuser 2:VU 2 : Assigning WID=251 based on VU count 10, Warehouses = 1500 (26 out of 150)
Vuser 2:VU 2 : Assigning WID=261 based on VU count 10, Warehouses = 1500 (27 out of 150)
Vuser 2:VU 2 : Assigning WID=271 based on VU count 10, Warehouses = 1500 (28 out of 150)
Vuser 2:VU 2 : Assigning WID=281 based on VU count 10, Warehouses = 1500 (29 out of 150)
Vuser 2:VU 2 : Assigning WID=291 based on VU count 10, Warehouses = 1500 (30 out of 150)
Vuser 2:VU 2 : Assigning WID=301 based on VU count 10, Warehouses = 1500 (31 out of 150)
Vuser 2:VU 2 : Assigning WID=311 based on VU count 10, Warehouses = 1500 (32 out of 150)
Vuser 2:VU 2 : Assigning WID=321 based on VU count 10, Warehouses = 1500 (33 out of 150)
Vuser 2:VU 2 : Assigning WID=331 based on VU count 10, Warehouses = 1500 (34 out of 150)
Vuser 2:VU 2 : Assigning WID=341 based on VU count 10, Warehouses = 1500 (35 out of 150)
Vuser 2:VU 2 : Assigning WID=351 based on VU count 10, Warehouses = 1500 (36 out of 150)
Vuser 2:VU 2 : Assigning WID=361 based on VU count 10, Warehouses = 1500 (37 out of 150)
Vuser 2:VU 2 : Assigning WID=371 based on VU count 10, Warehouses = 1500 (38 out of 150)
Vuser 2:VU 2 : Assigning WID=381 based on VU count 10, Warehouses = 1500 (39 out of 150)
Vuser 2:VU 2 : Assigning WID=391 based on VU count 10, Warehouses = 1500 (40 out of 150)
Vuser 2:VU 2 : Assigning WID=401 based on VU count 10, Warehouses = 1500 (41 out of 150)
Vuser 2:VU 2 : Assigning WID=411 based on VU count 10, Warehouses = 1500 (42 out of 150)
Vuser 2:VU 2 : Assigning WID=421 based on VU count 10, Warehouses = 1500 (43 out of 150)
Vuser 2:VU 2 : Assigning WID=431 based on VU count 10, Warehouses = 1500 (44 out of 150)
Vuser 2:VU 2 : Assigning WID=441 based on VU count 10, Warehouses = 1500 (45 out of 150)
Vuser 2:VU 2 : Assigning WID=451 based on VU count 10, Warehouses = 1500 (46 out of 150)
Vuser 2:VU 2 : Assigning WID=461 based on VU count 10, Warehouses = 1500 (47 out of 150)
Vuser 2:VU 2 : Assigning WID=471 based on VU count 10, Warehouses = 1500 (48 out of 150)
Vuser 2:VU 2 : Assigning WID=481 based on VU count 10, Warehouses = 1500 (49 out of 150)
Vuser 2:VU 2 : Assigning WID=491 based on VU count 10, Warehouses = 1500 (50 out of 150)
Vuser 2:VU 2 : Assigning WID=501 based on VU count 10, Warehouses = 1500 (51 out of 150)
Vuser 2:VU 2 : Assigning WID=511 based on VU count 10, Warehouses = 1500 (52 out of 150)
Vuser 2:VU 2 : Assigning WID=521 based on VU count 10, Warehouses = 1500 (53 out of 150)
Vuser 2:VU 2 : Assigning WID=531 based on VU count 10, Warehouses = 1500 (54 out of 150)
Vuser 2:VU 2 : Assigning WID=541 based on VU count 10, Warehouses = 1500 (55 out of 150)
Vuser 2:VU 2 : Assigning WID=551 based on VU count 10, Warehouses = 1500 (56 out of 150)
Vuser 2:VU 2 : Assigning WID=561 based on VU count 10, Warehouses = 1500 (57 out of 150)
Vuser 2:VU 2 : Assigning WID=571 based on VU count 10, Warehouses = 1500 (58 out of 150)
Vuser 2:VU 2 : Assigning WID=581 based on VU count 10, Warehouses = 1500 (59 out of 150)
Vuser 2:VU 2 : Assigning WID=591 based on VU count 10, Warehouses = 1500 (60 out of 150)
Vuser 2:VU 2 : Assigning WID=601 based on VU count 10, Warehouses = 1500 (61 out of 150)
Vuser 2:VU 2 : Assigning WID=611 based on VU count 10, Warehouses = 1500 (62 out of 150)
Vuser 2:VU 2 : Assigning WID=621 based on VU count 10, Warehouses = 1500 (63 out of 150)
Vuser 2:VU 2 : Assigning WID=631 based on VU count 10, Warehouses = 1500 (64 out of 150)
Vuser 2:VU 2 : Assigning WID=641 based on VU count 10, Warehouses = 1500 (65 out of 150)
Vuser 2:VU 2 : Assigning WID=651 based on VU count 10, Warehouses = 1500 (66 out of 150)
Vuser 2:VU 2 : Assigning WID=661 based on VU count 10, Warehouses = 1500 (67 out of 150)
Vuser 2:VU 2 : Assigning WID=671 based on VU count 10, Warehouses = 1500 (68 out of 150)
Vuser 2:VU 2 : Assigning WID=681 based on VU count 10, Warehouses = 1500 (69 out of 150)
Vuser 2:VU 2 : Assigning WID=691 based on VU count 10, Warehouses = 1500 (70 out of 150)
Vuser 2:VU 2 : Assigning WID=701 based on VU count 10, Warehouses = 1500 (71 out of 150)
Vuser 2:VU 2 : Assigning WID=711 based on VU count 10, Warehouses = 1500 (72 out of 150)
Vuser 2:VU 2 : Assigning WID=721 based on VU count 10, Warehouses = 1500 (73 out of 150)
Vuser 2:VU 2 : Assigning WID=731 based on VU count 10, Warehouses = 1500 (74 out of 150)
Vuser 2:VU 2 : Assigning WID=741 based on VU count 10, Warehouses = 1500 (75 out of 150)
Vuser 2:VU 2 : Assigning WID=751 based on VU count 10, Warehouses = 1500 (76 out of 150)
Vuser 2:VU 2 : Assigning WID=761 based on VU count 10, Warehouses = 1500 (77 out of 150)
Vuser 2:VU 2 : Assigning WID=771 based on VU count 10, Warehouses = 1500 (78 out of 150)
Vuser 2:VU 2 : Assigning WID=781 based on VU count 10, Warehouses = 1500 (79 out of 150)
Vuser 2:VU 2 : Assigning WID=791 based on VU count 10, Warehouses = 1500 (80 out of 150)
Vuser 2:VU 2 : Assigning WID=801 based on VU count 10, Warehouses = 1500 (81 out of 150)
Vuser 2:VU 2 : Assigning WID=811 based on VU count 10, Warehouses = 1500 (82 out of 150)
Vuser 2:VU 2 : Assigning WID=821 based on VU count 10, Warehouses = 1500 (83 out of 150)
Vuser 2:VU 2 : Assigning WID=831 based on VU count 10, Warehouses = 1500 (84 out of 150)
Vuser 2:VU 2 : Assigning WID=841 based on VU count 10, Warehouses = 1500 (85 out of 150)
Vuser 2:VU 2 : Assigning WID=851 based on VU count 10, Warehouses = 1500 (86 out of 150)
Vuser 2:VU 2 : Assigning WID=861 based on VU count 10, Warehouses = 1500 (87 out of 150)
Vuser 2:VU 2 : Assigning WID=871 based on VU count 10, Warehouses = 1500 (88 out of 150)
Vuser 2:VU 2 : Assigning WID=881 based on VU count 10, Warehouses = 1500 (89 out of 150)
Vuser 2:VU 2 : Assigning WID=891 based on VU count 10, Warehouses = 1500 (90 out of 150)
Vuser 2:VU 2 : Assigning WID=901 based on VU count 10, Warehouses = 1500 (91 out of 150)
Vuser 2:VU 2 : Assigning WID=911 based on VU count 10, Warehouses = 1500 (92 out of 150)
Vuser 2:VU 2 : Assigning WID=921 based on VU count 10, Warehouses = 1500 (93 out of 150)
Vuser 2:VU 2 : Assigning WID=931 based on VU count 10, Warehouses = 1500 (94 out of 150)
Vuser 2:VU 2 : Assigning WID=941 based on VU count 10, Warehouses = 1500 (95 out of 150)
Vuser 2:VU 2 : Assigning WID=951 based on VU count 10, Warehouses = 1500 (96 out of 150)
Vuser 2:VU 2 : Assigning WID=961 based on VU count 10, Warehouses = 1500 (97 out of 150)
Vuser 2:VU 2 : Assigning WID=971 based on VU count 10, Warehouses = 1500 (98 out of 150)
Vuser 2:VU 2 : Assigning WID=981 based on VU count 10, Warehouses = 1500 (99 out of 150)
Vuser 2:VU 2 : Assigning WID=991 based on VU count 10, Warehouses = 1500 (100 out of 150)
Vuser 2:VU 2 : Assigning WID=1001 based on VU count 10, Warehouses = 1500 (101 out of 150)
Vuser 2:VU 2 : Assigning WID=1011 based on VU count 10, Warehouses = 1500 (102 out of 150)
Vuser 2:VU 2 : Assigning WID=1021 based on VU count 10, Warehouses = 1500 (103 out of 150)
Vuser 2:VU 2 : Assigning WID=1031 based on VU count 10, Warehouses = 1500 (104 out of 150)
Vuser 2:VU 2 : Assigning WID=1041 based on VU count 10, Warehouses = 1500 (105 out of 150)
Vuser 2:VU 2 : Assigning WID=1051 based on VU count 10, Warehouses = 1500 (106 out of 150)
Vuser 2:VU 2 : Assigning WID=1061 based on VU count 10, Warehouses = 1500 (107 out of 150)
Vuser 2:VU 2 : Assigning WID=1071 based on VU count 10, Warehouses = 1500 (108 out of 150)
Vuser 2:VU 2 : Assigning WID=1081 based on VU count 10, Warehouses = 1500 (109 out of 150)
Vuser 2:VU 2 : Assigning WID=1091 based on VU count 10, Warehouses = 1500 (110 out of 150)
Vuser 2:VU 2 : Assigning WID=1101 based on VU count 10, Warehouses = 1500 (111 out of 150)
Vuser 2:VU 2 : Assigning WID=1111 based on VU count 10, Warehouses = 1500 (112 out of 150)
Vuser 2:VU 2 : Assigning WID=1121 based on VU count 10, Warehouses = 1500 (113 out of 150)
Vuser 2:VU 2 : Assigning WID=1131 based on VU count 10, Warehouses = 1500 (114 out of 150)
Vuser 2:VU 2 : Assigning WID=1141 based on VU count 10, Warehouses = 1500 (115 out of 150)
Vuser 2:VU 2 : Assigning WID=1151 based on VU count 10, Warehouses = 1500 (116 out of 150)
Vuser 2:VU 2 : Assigning WID=1161 based on VU count 10, Warehouses = 1500 (117 out of 150)
Vuser 2:VU 2 : Assigning WID=1171 based on VU count 10, Warehouses = 1500 (118 out of 150)
Vuser 2:VU 2 : Assigning WID=1181 based on VU count 10, Warehouses = 1500 (119 out of 150)
Vuser 2:VU 2 : Assigning WID=1191 based on VU count 10, Warehouses = 1500 (120 out of 150)
Vuser 2:VU 2 : Assigning WID=1201 based on VU count 10, Warehouses = 1500 (121 out of 150)
Vuser 2:VU 2 : Assigning WID=1211 based on VU count 10, Warehouses = 1500 (122 out of 150)
Vuser 2:VU 2 : Assigning WID=1221 based on VU count 10, Warehouses = 1500 (123 out of 150)
Vuser 2:VU 2 : Assigning WID=1231 based on VU count 10, Warehouses = 1500 (124 out of 150)
Vuser 2:VU 2 : Assigning WID=1241 based on VU count 10, Warehouses = 1500 (125 out of 150)
Vuser 2:VU 2 : Assigning WID=1251 based on VU count 10, Warehouses = 1500 (126 out of 150)
Vuser 2:VU 2 : Assigning WID=1261 based on VU count 10, Warehouses = 1500 (127 out of 150)
Vuser 2:VU 2 : Assigning WID=1271 based on VU count 10, Warehouses = 1500 (128 out of 150)
Vuser 2:VU 2 : Assigning WID=1281 based on VU count 10, Warehouses = 1500 (129 out of 150)
Vuser 2:VU 2 : Assigning WID=1291 based on VU count 10, Warehouses = 1500 (130 out of 150)
Vuser 2:VU 2 : Assigning WID=1301 based on VU count 10, Warehouses = 1500 (131 out of 150)
Vuser 2:VU 2 : Assigning WID=1311 based on VU count 10, Warehouses = 1500 (132 out of 150)
Vuser 2:VU 2 : Assigning WID=1321 based on VU count 10, Warehouses = 1500 (133 out of 150)
Vuser 2:VU 2 : Assigning WID=1331 based on VU count 10, Warehouses = 1500 (134 out of 150)
Vuser 2:VU 2 : Assigning WID=1341 based on VU count 10, Warehouses = 1500 (135 out of 150)
Vuser 2:VU 2 : Assigning WID=1351 based on VU count 10, Warehouses = 1500 (136 out of 150)
Vuser 2:VU 2 : Assigning WID=1361 based on VU count 10, Warehouses = 1500 (137 out of 150)
Vuser 2:VU 2 : Assigning WID=1371 based on VU count 10, Warehouses = 1500 (138 out of 150)
Vuser 2:VU 2 : Assigning WID=1381 based on VU count 10, Warehouses = 1500 (139 out of 150)
Vuser 2:VU 2 : Assigning WID=1391 based on VU count 10, Warehouses = 1500 (140 out of 150)
Vuser 2:VU 2 : Assigning WID=1401 based on VU count 10, Warehouses = 1500 (141 out of 150)
Vuser 2:VU 2 : Assigning WID=1411 based on VU count 10, Warehouses = 1500 (142 out of 150)
Vuser 2:VU 2 : Assigning WID=1421 based on VU count 10, Warehouses = 1500 (143 out of 150)
Vuser 2:VU 2 : Assigning WID=1431 based on VU count 10, Warehouses = 1500 (144 out of 150)
Vuser 2:VU 2 : Assigning WID=1441 based on VU count 10, Warehouses = 1500 (145 out of 150)
Vuser 2:VU 2 : Assigning WID=1451 based on VU count 10, Warehouses = 1500 (146 out of 150)
Vuser 2:VU 2 : Assigning WID=1461 based on VU count 10, Warehouses = 1500 (147 out of 150)
Vuser 2:VU 2 : Assigning WID=1471 based on VU count 10, Warehouses = 1500 (148 out of 150)
Vuser 2:VU 2 : Assigning WID=1481 based on VU count 10, Warehouses = 1500 (149 out of 150)
Vuser 2:VU 2 : Assigning WID=1491 based on VU count 10, Warehouses = 1500 (150 out of 150)
.....
Vuser 11:VU 11 : Assigning WID=1430 based on VU count 10, Warehouses = 1500 (143 out of 150)
Vuser 11:VU 11 : Assigning WID=1440 based on VU count 10, Warehouses = 1500 (144 out of 150)
Vuser 11:VU 11 : Assigning WID=1450 based on VU count 10, Warehouses = 1500 (145 out of 150)
Vuser 11:VU 11 : Assigning WID=1460 based on VU count 10, Warehouses = 1500 (146 out of 150)
Vuser 11:VU 11 : Assigning WID=1470 based on VU count 10, Warehouses = 1500 (147 out of 150)
Vuser 11:VU 11 : Assigning WID=1480 based on VU count 10, Warehouses = 1500 (148 out of 150)
Vuser 11:VU 11 : Assigning WID=1490 based on VU count 10, Warehouses = 1500 (149 out of 150)
Vuser 11:VU 11 : Assigning WID=1500 based on VU count 10, Warehouses = 1500 (150 out of 150)
```
It can be checked from the listing above that VU2 did select warehouses at random from its allocation changing for each transaction. 
```
Vuser 2:Chose Warehouse 1101 from my allocation
...
Vuser 2:Chose Warehouse 1451 from my allocation
...
Vuser 2:Chose Warehouse 611 from my allocation
...
Vuser 2:Chose Warehouse 501 from my allocation
...
Vuser 2:Chose Warehouse 1421 from my allocation
...
Vuser 2:Chose Warehouse 581 from my allocation
```
So for these tests warehouse selection for HammerDB v4.0 warehouse selection is correctly randomized and is choosing at random from the full available number of warehouses in this case 1500 for both the default approach and the use all warehouses. 

At present it is not possible to reproduce the Issue  "It looks like the warehouse selection in 4.0 is not randomized." - please provide further data to show where the problem lies.

**Comment by sm-shaw** [comment] 2021-01-20 10:39
@ek1220 can you provide any further information? Otherwise we will need to close this as not able to reproduce.

**Comment by sm-shaw** [comment] 2021-01-21 10:10
Closed as no further update and not possible to reproduce the issue.  Appears that screenshot was misinterpreted.

**Closed by sm-shaw** 2021-01-21 10:10 UTC

**Comment by ek1220** [comment] 2021-01-21 10:17
Yes, seems the output was misinterpreted. Thank you for testing.
my own testing has shown similar results.
